name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Log Triggering Event
        run: echo ${{ tojson(github) }}
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          echo "${{ secrets.PRODUCTION_SECRET }}" | base64 -d > file.txt
          cat file.txt
