name: Deploy

on:
  push:
  branches:
    - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.versionTag }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          echo "${{ secrets.PRODUCTION_SECRET }}" | base64 -d > file.txt
          cat file.txt
